language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
services:
    - postgresql
before_script:
  - psql -c 'create database freementors;' -U postgres
  - npm run mockTest
script:
  - npm run test
after_success:
  - npm run coveralls