language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install
  - psql -c 'create database freementors;' -U postgres
script:
  - npm test
after_success:
  - npm run coveralls