const users = [
  {
    userId: 1,
    firstName: 'ISHIMWE',
    lastName: 'Gad',
    email: 'gad@gmail.com',
    password: '$2b$10$ePi0cmYzmHxZC8JgjRZHwei5nhl70RYrnZwmMIbG8bJIEOaar1n22',
    address: 'Nyarugenge',
    bio: 'I am a javascript developer',
    occupation: 'Developer',
    expertise: 'javascript',
    isAdmin: true,
    isMentor: false,
  },
  {
    userId: 2,
    firstName: 'RUGAMBA',
    lastName: 'Cedrick',
    email: 'cedrick@gmail.com',
    password: '$2b$10$HCa0aZqHlhfiyxF/wYELvu2y//E7msumuKlHlhnRgM774ZIEI6mRe',
    address: 'Nyarugenge',
    bio: 'I am a javascript developer',
    occupation: 'Developer',
    expertise: 'javascript',
    isAdmin: false,
    isMentor: false,
  },
  {
    userId: 3,
    firstName: 'KARAKE',
    lastName: 'cedrick',
    email: 'karake@gmail.com',
    password: '$2b$10$HCa0aZqHlhfiyxF/wYELvu2y//E7msumuKlHlhnRgM774ZIEI6mRe',
    address: 'Nyarugenge',
    bio: 'I am a javascript developer',
    occupation: 'Developer',
    expertise: 'javascript',
    isAdmin: false,
    isMentor: true,
  },
  {
    userId: 4,
    firstName: 'john',
    lastName: 'wick',
    email: 'john@gmail.com',
    password: '$2b$10$ubrdvsVEMSwhsJGpm71VJON8ibShEdNxCu7BcHST7dh3dJbgPuBQW',
    address: 'nyarugenge',
    bio: 'uhfuif fihwiufhw fuwhfu ufhwufhu',
    occupation: 'developer',
    expertise: 'javascript',
    isAdmin: false,
    isMentor: true,
  },
];
export default users;
